const insults = {
  light: [
    "You're the reason autocorrect gave up.",
    "You bring everyone so much joy… when you leave.",
    "You're not stupid; you just have bad luck thinking.",
    "You're like a cloud—when you disappear, it’s a beautiful day.",
    "You have something on your chin… no, the third one down.",
    "You're not the sharpest pixel on the screen.",
    "You're like a Monday — nobody likes you.",
    "You have the energy of a drained battery.",
    "You're as useless as a white crayon.",
    "You're the human version of a pop-up ad.",
    "You're like a software update — annoying and unnecessary.",
    "You're not weird — you're limited edition boring.",
    "You're like a puzzle with missing pieces.",
    "You're more disappointing than an unsalted fry.",
    "You're the human equivalent of buffering.",
    "You're like a selfie with no filter — just sad.",
    "You're not even the main character in your own story.",
    "You're like a donut without filling — hollow.",
    "You make sloths look productive.",
    "You're like an expired coupon — pointless.",
    "You bring as much value as a dead pixel.",
    "You're like a salad at a pizza party.",
    "You're like a tutorial with no sound.",
    "You're like a joke with no punchline.",
    "You're like a screenshot of a QR code — useless.",
    "You're a few fries short of a happy meal.",
    "You're like Bluetooth — always disconnecting.",
    "You couldn’t pour water out of a boot with instructions on the heel.",
    "You have a face for podcasting.",
    "You're like an app that crashes on launch.",
    "You have the charisma of wet cardboard.",
    "You’re the reason mute buttons exist.",
    "You have less personality than a captcha.",
    "You're the reason doors have peepholes.",
    "You're like static on the radio — annoying and pointless.",
    "You're about as original as a chain email.",
    "You're more forgettable than a printer manual.",
    "You’re the opposite of a life hack.",
    "You’re like incognito mode — useless when it counts.",
    "You're as sharp as a marble.",
    "You’re the backup character in a tutorial.",
    "You're like diet water — confusing and unnecessary.",
    "You’re like a clock with no hands — always behind.",
    "You're like a toaster in a bathtub — a terrible idea.",
    "You're like autocorrect in a breakup text — chaotic.",
    "You're like a printer with no ink — empty.",
    "You're like a seatbelt on a couch — why are you even there?",
    "You're the punchline no one laughs at.",
    "You're like a flip phone in 2025.",
    "You're the reason the skip intro button exists.",
    "You're like a review with no stars."
  ],
  spicy: [
    "You're like a software update at 2AM — nobody asked for you.",
    "You're proof that evolution can go in reverse.",
    "You have the charm of a soggy tissue.",
    "You're about as useful as a semicolon in JavaScript.",
    "You bring chaos wherever you go — and not the fun kind.",
    "You're like a group chat with your exes.",
    "You have less sense than a screen door on a submarine.",
    "You're more fake than a staged prank video.",
    "You're a walking WiFi dead zone.",
    "You're like Ctrl+Z in real life — doesn't exist.",
    "You're about as organized as a dropped lasagna.",
    "You're like a captcha that never loads.",
    "You're like a password reset email that never comes.",
    "You're the reason aliens don’t visit.",
    "You're the human version of a 404 page.",
    "You're as stable as a Windows ME system.",
    "You couldn't lead a silent prayer.",
    "You're like a power outlet with no electricity.",
    "You're like a spicy take with no flavor.",
    "You're like an online date gone offline.",
    "You're like a notification with no purpose.",
    "You're as welcome as a pop quiz.",
    "You're like a sticker on fruit — always in the way.",
    "You bring confusion like a missing remote.",
    "You're like incognito mode — everyone knows you're still there.",
    "You're the type to fail an open-book test.",
    "You're like bad WiFi in a Zoom call.",
    "You're like a Tinder match who only sends emojis.",
    "You're like a cracked screen — still usable, but sad.",
    "You're a drama queen in a low-budget soap opera.",
    "You're like a light bulb that flickers forever.",
    "You're like a hangnail during a handshake.",
    "You’re more toxic than a Reddit comment thread.",
    "You're like a bug in production code.",
    "You're like a browser with 100 open tabs — and no idea where the music's coming from.",
    "You're the final boss of awkward.",
    "You're more bitter than cold coffee.",
    "You're like an ice cream cone dropped on hot concrete.",
    "You're the human form of a dropped call.",
    "You're like a dad joke that never lands.",
    "You're like an alarm clock on a Saturday.",
    "You're the secondhand embarrassment in human form.",
    "You're the tab that starts playing music randomly.",
    "You're the typo in a tattoo.",
    "You're like the wrong GIF in a breakup message.",
    "You're a walking error message.",
    "You're like a keyboard with sticky keys.",
    "You're the blue screen of people.",
    "You're like an influencer with no WiFi.",
    "You're like spam mail — always unwanted.",
    "You're like a Zoom filter gone wrong."
  ],
  shakespearean: [
    "Thou art as useless as the 'g' in lasagna.",
    "Thy wit's as sharp as a butter knife.",
    "Thou hath the grace of a drunken walrus.",
    "Thou art a boil, a plague sore, an embossed carbuncle.",
    "Thy brain is as dry as a biscuit.",
    "Thou smell of mountain goat.",
    "Thy face is not worth sunburning.",
    "Thy tongue outvenoms all the worms of Nile.",
    "Thou art a flesh-monger, a fool and a coward.",
    "Thy breath offends more than a dragon’s rear.",
    "Thou art as loathsome as a toad.",
    "Thou wearest a skull thick as an ale barrel.",
    "Thou art an unwashed toad-spawn.",
    "Thou hath more hair than wit.",
    "Thy stupidity maketh rocks seem wise.",
    "Thou art as base as a churlish dog.",
    "Thou art a fusty nut with no kernel.",
    "Thou art born to make insults seem flattery.",
    "Thy mind is as empty as a beggar’s purse.",
    "Thy presence is as welcome as the pox.",
    "Thou art a canker blossom on society’s rose.",
    "Thy soul doth leak foolishness.",
    "Thou art more scurvy than a sailor's beard.",
    "Thou speak'st nonsense like a drunken bard.",
    "Thou reek'st like old boots left in rain.",
    "Thy words are as dry as summer dust.",
    "Thou art less noble than a fart in court.",
    "Thou art a babbling hedgehog.",
    "Thy intellect is dimmer than a taper’s end.",
    "Thou art an insult to thine ancestors.",
    "Thy speech is as stale as yesterday's bread.",
    "Thou art a plague in human shape.",
    "Thy thoughts limp like a lame jester.",
    "Thou art a pie crust filled with air.",
    "Thy name is forgotten ere it’s spoken.",
    "Thy honor is thinner than parchment.",
    "Thou art a villain in peasant's garb.",
    "Thou smell of wet parchment and failure.",
    "Thy face hath scared the owls to flight.",
    "Thy brain is as useful as a sieve with soup.",
    "Thy voice crackles like cursed scrolls.",
    "Thou art the barnacle on society’s hull.",
    "Thy legacy shall be forgotten mid-sentence.",
    "Thy presence tires the very sun.",
    "Thou art as wanted as lice on linen.",
    "Thy logic is but a ship in shallow waters.",
    "Thou art the jest of jesters.",
    "Thy heart is colder than a witch’s smile.",
    "Thou art the dust beneath a beggar's foot.",
    "Thou art the echo of foolishness in a vast cave."
  ]
};

function random(level = "light") {
  const list = insults[level] || insults.light;
  return list[Math.floor(Math.random() * list.length)];
}

function list(count = 5, level = "light") {
  const result = [];
  for (let i = 0; i < count; i++) {
    result.push(random(level));
  }
  return result;
}

function custom({ target = "You", level = "light" } = {}) {
  const burn = random(level);
  return `${target}, ${burn.charAt(0).toLowerCase() + burn.slice(1)}`;
}

module.exports = {
  random,
  list,
  custom
};
